import { slugify } from "./slug";

export interface SeedProperty {
  id: string;
  slug: string;
  name: string;
  branded_name: string;
  building_name: string;
  city: string;
  neighbourhood: string;
  neighbourhood_slug: string;
  building_slug: string;
  country: string;
  description: string;
  amenities: string[];
  route_note: string;
  bedrooms: number;
  bathrooms?: number;
  sleeps: number;
  nightly_rate_minor: number;
  deposit_minor: number;
  currency: string;
  extended_checkout_offered: boolean;
  extended_checkout_price_minor: number | null;
  is_featured: boolean;
  status: string;
  images: string[];
  cover_photo_url: string | null;
  owner_id?: string;
}

export interface SeedReservation {
  id: string;
  property_id: string;
  check_in: string;
  check_out: string;
  status: string;
}

export interface SeedBlock {
  property_id: string;
  starts: string;
  ends: string;
  source: string;
}

export interface SeedOperator {
  id: string;
  name: string;
  phone: string;
  city: string;
  email?: string;
}

export interface SeedInspection {
  id: string;
  property_id: string;
  property_name: string;
  unit: string;
  guest_name: string;
  checkout_date: string;
  checkout_time: string;
  status: "pending" | "in_progress" | "completed" | "escalated";
  confirmed_checkout_time: string | null;
}

export interface SeedDamageClaim {
  id: string;
  reservation_id: string;
  property_name: string;
  property_id: string;
  guest_name: string;
  guest_email: string;
  booking_ref: string;
  stay_dates: string;
  description: string;
  estimated_cost_minor: number;
  operator_notes: string;
  photo_count: number;
  admin_decision: string;
  adjusted_amount_minor: number | null;
  dispute_status: string;
  submitted_at: string;
  decided_at: string | null;
  decided_by: string | null;
  photos: string[];
}

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`;

// Fresh image pool — none of these IDs appear in PR001–PR006
const I = {
  a: "photo-1618220179428-22790b461013",
  b: "photo-1616486029423-aaa4789e8c9a",
  c: "photo-1512917774080-9991f1c4c750",
  d: "photo-1616594039964-ae9021a400a0",
  e: "photo-1600047509807-ba8f99d2cdde",
  f: "photo-1586023492125-27b2c045efd7",
  g: "photo-1616137466211-f939a420be84",
  h: "photo-1600607687920-4e2a09cf159d",
  i: "photo-1600596542815-ffad4c1539a9",
  j: "photo-1600607687939-ce8a6c25118c",
  k: "photo-1600566753190-17f0baa2a6c3",
  l: "photo-1600210492486-724fe5c67fb0",
  m: "photo-1590490360182-c33d57733427",
  n: "photo-1540518614846-7eded433c457",
  o: "photo-1502672260266-1c1ef2d93688",
  p: "photo-1493809842364-78817add7ffb",
  q: "photo-1600585154084-4e5fe7c39198",
  r: "photo-1524758631624-e2822e304c36",
  s: "photo-1600607687939-ce8a6c25118c",
  t: "photo-1574362848149-11496d93a7c7",
};

function imgs(...ids: string[]): string[] {
  return ids.map(img);
}

export function getSeedProperties(): SeedProperty[] {
  const ownerMap: Record<string, string> = {
    PR001: "OW1", PR002: "OW1", PR003: "OW1", PR004: "OW1", PR005: "OW1",
    PR006: "OW2", PR007: "OW2", PR008: "OW2", PR009: "OW2", PR010: "OW2",
    PR011: "OW3", PR012: "OW3", PR013: "OW3", PR014: "OW3", PR015: "OW3",
    PR016: "OW4", PR017: "OW4", PR018: "OW4", PR019: "OW4", PR020: "OW4",
    PR021: "OW5", PR022: "OW5", PR023: "OW5", PR024: "OW5", PR025: "OW5",
    PR026: "OW6", PR027: "OW6", PR028: "OW6", PR029: "OW6", PR030: "OW6",
  };
  const props = buildProperties();
  return props.map((p) => ({ ...p, owner_id: ownerMap[p.id] ?? "OW1" }));
}

function buildProperties(): Omit<SeedProperty, "owner_id">[] {
  return [
    // ── Existing 6 properties (PR001–PR006) — unchanged ──
    {
      id: "PR001",
      slug: "lagoon-view-loft",
      name: "Lagoon View Loft",
      branded_name: "Lagoon View Loft",
      building_name: "Ocean Parade Towers",
      city: "Lagos",
      neighbourhood: "Victoria Island",
      neighbourhood_slug: slugify("Victoria Island"),
      building_slug: slugify("Ocean Parade Towers"),
      country: "Nigeria",
      description: "Floor-to-ceiling windows frame the lagoon from this light-filled one-bedroom loft in the heart of Victoria Island. Minimalist interiors, curated art, and a private balcony make this the perfect base for exploring Lagos.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Kitchen", "Balcony", "Pool access", "24/7 security"],
      route_note: "15 min from Lagos airport (LOS). Secure parking available in the building.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 24000,
      deposit_minor: 10000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 9600,
      is_featured: true,
      status: "approved",
      images: imgs("photo-1600596542815-ffad4c1539a9", "photo-1600585154340-be6161a56a0c", "photo-1600607687939-ce8a6c25118c"),
      cover_photo_url: img("photo-1600596542815-ffad4c1539a9"),
    },
    {
      id: "PR002",
      slug: "sunset-dove",
      name: "Sunset Dove",
      branded_name: "Sunset Dove",
      building_name: "The Wings Complex",
      city: "Lagos",
      neighbourhood: "Ikoyi",
      neighbourhood_slug: slugify("Ikoyi"),
      building_slug: slugify("The Wings Complex"),
      country: "Nigeria",
      description: "A tranquil Ikoyi retreat with rooftop sunset views across Lagos. Mid-century furniture meets Nigerian craftsmanship in this thoughtfully composed one-bedroom apartment.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Kitchen", "Rooftop", "Gym", "Parking"],
      route_note: "20 min from LOS. Off Awolowo Road — easy taxi access.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 16000,
      deposit_minor: 10000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 6400,
      is_featured: false,
      status: "approved",
      images: imgs("photo-1600573472591-ee6b68d14c68", "photo-1560448204-e02f11c3d0e2", "photo-1600566753190-17f0baa2a6c3"),
      cover_photo_url: img("photo-1600573472591-ee6b68d14c68"),
    },
    {
      id: "PR003",
      slug: "the-palms-maisonette",
      name: "The Palms Maisonette",
      branded_name: "The Palms Maisonette",
      building_name: "Ahmadu Bello Mansions",
      city: "Lagos",
      neighbourhood: "Victoria Island",
      neighbourhood_slug: slugify("Victoria Island"),
      building_slug: slugify("Ahmadu Bello Mansions"),
      country: "Nigeria",
      description: "A spacious two-bedroom maisonette across two floors, featuring a private garden courtyard, dedicated workspace, and a fully equipped kitchen. Ideal for families or longer stays.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Kitchen", "Garden", "Workspace", "Parking", "Generator backup"],
      route_note: "10 min from LOS. On Ahmadu Bello Way.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 21000,
      deposit_minor: 15000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 8400,
      is_featured: true,
      status: "approved",
      images: imgs("photo-1600585154084-4e5fe7c39198", "photo-1600210492486-724fe5c67fb0", "photo-1600210492486-724fe5c67fb0"),
      cover_photo_url: img("photo-1600585154084-4e5fe7c39198"),
    },
    {
      id: "PR004",
      slug: "gra-executive-suite",
      name: "GRA Executive Suite",
      branded_name: "GRA Executive Suite",
      building_name: "Diplomatic Gardens",
      city: "Abuja",
      neighbourhood: "GRA",
      neighbourhood_slug: slugify("GRA"),
      building_slug: slugify("Diplomatic Gardens"),
      country: "Nigeria",
      description: "A refined two-bedroom suite in the heart of GRA, Abuja's most prestigious district. Marble floors, a formal dining room, and a private terrace overlook the diplomatic quarter.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Kitchen", "Terrace", "Pool", "Gym", "Parking", "Housekeeping"],
      route_note: "30 min from Abuja airport (ABV). In the GRA diplomatic zone.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 55000,
      deposit_minor: 25000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 22000,
      is_featured: true,
      status: "approved",
      images: imgs("photo-1600210492486-724fe5c67fb0", "photo-1600607687939-ce8a6c25118c", "photo-1600585154340-be6161a56a0c"),
      cover_photo_url: img("photo-1600210492486-724fe5c67fb0"),
    },
    {
      id: "PR005",
      slug: "maitama-garden-studios",
      name: "Maitama Garden Studios",
      branded_name: "Maitama Garden Studios",
      building_name: "Yakubu Gowon Gardens",
      city: "Abuja",
      neighbourhood: "Maitama",
      neighbourhood_slug: slugify("Maitama"),
      building_slug: slugify("Yakubu Gowon Gardens"),
      country: "Nigeria",
      description: "Light-filled studio apartments in a lush garden compound in Maitama. Each unit opens onto a shared tropical garden. Minimal, modern, and perfectly positioned for exploring Abuja.",
      amenities: ["WiFi", "Air conditioning", "Kitchenette", "Garden", "Laundry service", "Security"],
      route_note: "25 min from ABV. Off Yakubu Gowon Crescent.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 32000,
      deposit_minor: 10000,
      currency: "GBP",
      extended_checkout_offered: false,
      extended_checkout_price_minor: null,
      is_featured: false,
      status: "approved",
      images: imgs("photo-1600607687939-ce8a6c25118c", "photo-1600047509807-ba8f99d2cdde", "photo-1600607687920-4e2a09cf159d"),
      cover_photo_url: img("photo-1600607687939-ce8a6c25118c"),
    },
    {
      id: "PR006",
      slug: "central-abuja-penthouse",
      name: "Central Abuja Penthouse",
      branded_name: "Central Abuja Penthouse",
      building_name: "Millennium Tower Residences",
      city: "Abuja",
      neighbourhood: "Central District",
      neighbourhood_slug: slugify("Central District"),
      building_slug: slugify("Millennium Tower Residences"),
      country: "Nigeria",
      description: "A dramatic penthouse on the top floor of a Central District tower. Panoramic views across the capital, a private rooftop terrace, and interiors designed by a leading Lagos studio.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Rooftop terrace", "Pool", "Gym", "Valet parking", "Concierge"],
      route_note: "20 min from ABV. Walking distance to the Millennium Tower.",
      bedrooms: 3,
      sleeps: 6,
      nightly_rate_minor: 75000,
      deposit_minor: 30000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 30000,
      is_featured: true,
      status: "approved",
      images: imgs("photo-1600607687920-4e2a09cf159d", "photo-1600596542815-ffad4c1539a9", "photo-1599809275671-b5942cabc7a2"),
      cover_photo_url: img("photo-1600607687920-4e2a09cf159d"),
    },

    // ── New Lagos properties (PR007–PR018) ──
    {
      id: "PR007",
      slug: "ikoyi-courtyard-suite",
      name: "Ikoyi Courtyard Suite",
      branded_name: "Ikoyi Courtyard Suite",
      building_name: "Bourdillon Place",
      city: "Lagos",
      neighbourhood: "Ikoyi",
      neighbourhood_slug: slugify("Ikoyi"),
      building_slug: slugify("Bourdillon Place"),
      country: "Nigeria",
      description: "A serene garden-level suite tucked behind the Bourdillon Road bustle. Whitewashed walls, handwoven textiles, and a private courtyard shaded by century-old mango trees. Walking distance to the Ikoyi Club and the best restaurants on Keffi Street.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Kitchenette", "Private courtyard", "Garden access", "24/7 security", "Parking"],
      route_note: "18 min from LOS. Off Bourdillon Road, Ikoyi.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 18000,
      deposit_minor: 10000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 7200,
      is_featured: false,
      status: "approved",
      images: imgs(I.a, I.b, I.c),
      cover_photo_url: img(I.a),
    },
    {
      id: "PR008",
      slug: "lekki-lagoon-house",
      name: "Lekki Lagoon House",
      branded_name: "Lekki Lagoon House",
      building_name: "Lagoon Edge Estate",
      city: "Lagos",
      neighbourhood: "Lekki Phase 1",
      neighbourhood_slug: slugify("Lekki Phase 1"),
      building_slug: slugify("Lagoon Edge Estate"),
      country: "Nigeria",
      description: "Wide open living spaces facing the Lagos Lagoon. This two-bedroom gem combines a minimalist Japanese wabi-sabi aesthetic with bold Nigerian contemporary art. Floor-to-ceiling sliders blur the line between indoors and the waterfront deck.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Waterfront deck", "Outdoor shower", "Parking", "Generator backup", "Pool access"],
      route_note: "25 min from LOS. In Lagoon Edge Estate, Lekki Phase 1.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 28000,
      deposit_minor: 15000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 11200,
      is_featured: true,
      status: "approved",
      images: imgs(I.d, I.e, I.f),
      cover_photo_url: img(I.d),
    },
    {
      id: "PR009",
      slug: "surulere-music-room",
      name: "Surulere Music Room",
      branded_name: "Surulere Music Room",
      building_name: "Ita Faaji Lofts",
      city: "Lagos",
      neighbourhood: "Surulere",
      neighbourhood_slug: slugify("Surulere"),
      building_slug: slugify("Ita Faaji Lofts"),
      country: "Nigeria",
      description: "A creative's hideout in the cultural heart of Surulere. Vintage vinyl, a dedicated listening nook, and walls lined with Afrobeats gold records. The rooftop host nightly views of the Lagos mainland skyline.",
      amenities: ["WiFi", "Air conditioning", "Kitchenette", "Rooftop", "Record player", "Workspace", "Security"],
      route_note: "20 min from LOS. Off Adeniran Ogunsanya Street.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 15000,
      deposit_minor: 8000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 6000,
      is_featured: false,
      status: "approved",
      images: imgs(I.g, I.h, I.i),
      cover_photo_url: img(I.g),
    },
    {
      id: "PR010",
      slug: "yaba-hub-studio",
      name: "Yaba Hub Studio",
      branded_name: "Yaba Hub Studio",
      building_name: "Tech Bridge House",
      city: "Lagos",
      neighbourhood: "Yaba",
      neighbourhood_slug: slugify("Yaba"),
      building_slug: slugify("Tech Bridge House"),
      country: "Nigeria",
      description: "Sleek micro-apartment in the heart of Yaba's tech corridor. Walking distance to Co-Creation Hub and the best cafes on Commercial Avenue. Smart locks, gigabit fibre, and an ergonomic standing desk make this ideal for remote workers.",
      amenities: ["WiFi", "Air conditioning", "Kitchenette", "Standing desk", "Smart lock", "Laundry", "Security"],
      route_note: "12 min from LOS. On Commercial Avenue, Yaba.",
      bedrooms: 1,
      sleeps: 1,
      nightly_rate_minor: 14000,
      deposit_minor: 8000,
      currency: "GBP",
      extended_checkout_offered: false,
      extended_checkout_price_minor: null,
      is_featured: false,
      status: "approved",
      images: imgs(I.j, I.k, I.l),
      cover_photo_url: img(I.j),
    },
    {
      id: "PR011",
      slug: "banana-island-villa",
      name: "Banana Island Villa",
      branded_name: "Banana Island Villa",
      building_name: "Banana Island Estate",
      city: "Lagos",
      neighbourhood: "Banana Island",
      neighbourhood_slug: slugify("Banana Island"),
      building_slug: slugify("Banana Island Estate"),
      country: "Nigeria",
      description: "A sprawling three-bedroom villa on Lagos's most exclusive reclaimed island. Private infinity pool, imported Italian marble, a chef's kitchen, and a rooftop bar overlooking the Atlantic. The benchmark for luxury short-stay in Lagos.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Infinity pool", "Rooftop bar", "Gym", "Valet parking", "24/7 security", "Housekeeping", "Generator backup"],
      route_note: "30 min from LOS. Inside Banana Island Estate — security checkpoint.",
      bedrooms: 3,
      sleeps: 6,
      nightly_rate_minor: 45000,
      deposit_minor: 20000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 18000,
      is_featured: true,
      status: "approved",
      images: imgs(I.m, I.n, I.o),
      cover_photo_url: img(I.m),
    },
    {
      id: "PR012",
      slug: "sixth-floor-vista",
      name: "Sixth Floor Vista",
      branded_name: "Sixth Floor Vista",
      building_name: "Marina Heights",
      city: "Lagos",
      neighbourhood: "Victoria Island",
      neighbourhood_slug: slugify("Victoria Island"),
      building_slug: slugify("Marina Heights"),
      country: "Nigeria",
      description: "An airy one-bedroom perched high above Victoria Island's marina. The view takes in the entire Lagos coastline, from Tarkwa Bay to the Third Mainland Bridge. Monochrome palette punctuated by tropical greenery.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Kitchen", "Balcony", "Pool", "Gym", "Parking", "Concierge"],
      route_note: "15 min from LOS. On Marina, Victoria Island.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 22000,
      deposit_minor: 12000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 8800,
      is_featured: false,
      status: "approved",
      images: imgs(I.p, I.q, I.r),
      cover_photo_url: img(I.p),
    },
    {
      id: "PR013",
      slug: "lekki-garden-duplex",
      name: "Lekki Garden Duplex",
      branded_name: "Lekki Garden Duplex",
      building_name: "Garden Court Estate",
      city: "Lagos",
      neighbourhood: "Lekki Phase 1",
      neighbourhood_slug: slugify("Lekki Phase 1"),
      building_slug: slugify("Garden Court Estate"),
      country: "Nigeria",
      description: "A bi-level duplex wrapped around a private garden with an open-plan kitchen, dining, and living area flowing onto a sun-drenched terrace. Smart home controls, a dedicated office nook, and two en-suite bedrooms upstairs.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Garden", "Terrace", "Smart home", "Workspace", "Parking", "Generator backup"],
      route_note: "25 min from LOS. Inside Garden Court Estate, Lekki Phase 1.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 32000,
      deposit_minor: 15000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 12800,
      is_featured: true,
      status: "approved",
      images: imgs(I.s, I.t, I.a),
      cover_photo_url: img(I.s),
    },
    {
      id: "PR014",
      slug: "awolowo-residence",
      name: "Awolowo Residence",
      branded_name: "Awolowo Residence",
      building_name: "Awolowo Place",
      city: "Lagos",
      neighbourhood: "Ikoyi",
      neighbourhood_slug: slugify("Ikoyi"),
      building_slug: slugify("Awolowo Place"),
      country: "Nigeria",
      description: "A calm two-bedroom residence on quiet Awolowo Road. Herringbone timber floors, a powder room, and a spacious living area that opens onto a leafy balcony. Steps from Ikoyi's best dining and the green expanse of Falomo.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Balcony", "Parking", "24/7 security", "Housekeeping"],
      route_note: "18 min from LOS. Off Awolowo Road, Ikoyi.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 26000,
      deposit_minor: 15000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 10400,
      is_featured: false,
      status: "approved",
      images: imgs(I.b, I.c, I.d),
      cover_photo_url: img(I.b),
    },
    {
      id: "PR015",
      slug: "surulere-attic-loft",
      name: "Surulere Attic Loft",
      branded_name: "Surulere Attic Loft",
      building_name: "Bode Thomas House",
      city: "Lagos",
      neighbourhood: "Surulere",
      neighbourhood_slug: slugify("Surulere"),
      building_slug: slugify("Bode Thomas House"),
      country: "Nigeria",
      description: "A converted attic in a 1970s Surulere apartment block. Exposed beam ceilings, a mezzanine sleeping area, and a sunny reading corner. The neighbourhood hums with street food, live music, and local energy.",
      amenities: ["WiFi", "Air conditioning", "Kitchenette", "Mezzanine", "Reading nook", "Laundry", "Security"],
      route_note: "20 min from LOS. On Bode Thomas Street, Surulere.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 16000,
      deposit_minor: 8000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 6400,
      is_featured: false,
      status: "approved",
      images: imgs(I.e, I.f, I.g),
      cover_photo_url: img(I.e),
    },
    {
      id: "PR016",
      slug: "banana-island-terrace",
      name: "Banana Island Terrace",
      branded_name: "Banana Island Terrace",
      building_name: "Parkview Estate",
      city: "Lagos",
      neighbourhood: "Banana Island",
      neighbourhood_slug: slugify("Banana Island"),
      building_slug: slugify("Parkview Estate"),
      country: "Nigeria",
      description: "Grand three-bedroom apartment with a wraparound terrace across the entire frontage. Soaring ceilings, a wine room, and a media lounge. The master suite features a spa-inspired bathroom with a freestanding soaking tub.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Wraparound terrace", "Wine room", "Media lounge", "Pool", "Gym", "Parking", "24/7 security"],
      route_note: "30 min from LOS. Inside Parkview Estate, Banana Island.",
      bedrooms: 3,
      sleeps: 6,
      nightly_rate_minor: 50000,
      deposit_minor: 25000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 20000,
      is_featured: true,
      status: "approved",
      images: imgs(I.h, I.i, I.j),
      cover_photo_url: img(I.h),
    },
    {
      id: "PR017",
      slug: "yaba-fibre-studio",
      name: "Yaba Fibre Studio",
      branded_name: "Yaba Fibre Studio",
      building_name: "Herbert Macaulay House",
      city: "Lagos",
      neighbourhood: "Yaba",
      neighbourhood_slug: slugify("Yaba"),
      building_slug: slugify("Herbert Macaulay House"),
      country: "Nigeria",
      description: "Compact, cleverly designed studio steps from the Yaba Railway Station. Hospital- grade air filtration, soundproofed windows, a Murphy bed, and a fold-down desk. Optimised for deep focus and deep sleep.",
      amenities: ["WiFi", "Air conditioning", "Kitchenette", "Soundproofing", "Murphy bed", "Laundry", "Security"],
      route_note: "12 min from LOS. On Herbert Macaulay Way, Yaba.",
      bedrooms: 1,
      sleeps: 1,
      nightly_rate_minor: 14000,
      deposit_minor: 8000,
      currency: "GBP",
      extended_checkout_offered: false,
      extended_checkout_price_minor: null,
      is_featured: false,
      status: "approved",
      images: imgs(I.k, I.l, I.m),
      cover_photo_url: img(I.k),
    },
    {
      id: "PR018",
      slug: "victoria-island-garden-flat",
      name: "Victoria Island Garden Flat",
      branded_name: "Victoria Island Garden Flat",
      building_name: "River Valley Estate",
      city: "Lagos",
      neighbourhood: "Victoria Island",
      neighbourhood_slug: slugify("Victoria Island"),
      building_slug: slugify("River Valley Estate"),
      country: "Nigeria",
      description: "A ground-floor flat where the garden is an extension of the living room. Bioline doors fold completely open to a lawn dotted with frangipani and a private plunge pool. The bedroom has direct garden access with an outdoor rain shower.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Kitchen", "Private garden", "Plunge pool", "Outdoor shower", "Parking", "Security"],
      route_note: "15 min from LOS. In River Valley Estate, Victoria Island.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 20000,
      deposit_minor: 10000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 8000,
      is_featured: false,
      status: "approved",
      images: imgs(I.n, I.o, I.p),
      cover_photo_url: img(I.n),
    },

    // ── New Abuja properties (PR019–PR030) ──
    {
      id: "PR019",
      slug: "asokoro-state-house-view",
      name: "Asokoro State House View",
      branded_name: "Asokoro State House View",
      building_name: "Presidential Gardens Estate",
      city: "Abuja",
      neighbourhood: "Asokoro",
      neighbourhood_slug: slugify("Asokoro"),
      building_slug: slugify("Presidential Gardens Estate"),
      country: "Nigeria",
      description: "A sophisticated two-bedroom apartment facing Aso Rock. Every window frames the seat of Nigerian power. Neutral tones accented with burnt orange and indigo. The residents' lounge has a whisky bar and cigar terrace.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Residents lounge", "Whisky bar", "Pool", "Gym", "Valet parking", "24/7 security"],
      route_note: "25 min from ABV. Inside Presidential Gardens Estate, Asokoro.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 38000,
      deposit_minor: 20000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 15200,
      is_featured: true,
      status: "approved",
      images: imgs(I.q, I.r, I.s),
      cover_photo_url: img(I.q),
    },
    {
      id: "PR020",
      slug: "wuse-2-executive",
      name: "Wuse 2 Executive",
      branded_name: "Wuse 2 Executive",
      building_name: "Adetokunbo Ademola Towers",
      city: "Abuja",
      neighbourhood: "Wuse 2",
      neighbourhood_slug: slugify("Wuse 2"),
      building_slug: slugify("Adetokunbo Ademola Towers"),
      country: "Nigeria",
      description: "A business-ready two-bedroom in the commercial heart of Wuse 2. Dedicated meeting room with video conferencing, a fully stocked Nespresso bar, and a balcony overlooking the bustle of Adetokunbo Ademola Street.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Meeting room", "Nespresso bar", "Balcony", "Parking", "Business centre", "Security"],
      route_note: "20 min from ABV. On Adetokunbo Ademola Street, Wuse 2.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 30000,
      deposit_minor: 15000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 12000,
      is_featured: false,
      status: "approved",
      images: imgs(I.t, I.a, I.b),
      cover_photo_url: img(I.t),
    },
    {
      id: "PR021",
      slug: "jabi-lake-studios",
      name: "Jabi Lake Studios",
      branded_name: "Jabi Lake Studios",
      building_name: "Lake View Crescent",
      city: "Abuja",
      neighbourhood: "Jabi",
      neighbourhood_slug: slugify("Jabi"),
      building_slug: slugify("Lake View Crescent"),
      country: "Nigeria",
      description: "Compact studio with a front-row seat to Jabi Lake. Floor-to-ceiling windows capture the sunset over the water. The building has a lakefront restaurant, a small gym, and 24-hour security. Walk to Jabi Lake Mall.",
      amenities: ["WiFi", "Air conditioning", "Kitchenette", "Lake view", "Restaurant access", "Gym", "Security", "Parking"],
      route_note: "20 min from ABV. Off Lake View Crescent, Jabi.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 25000,
      deposit_minor: 10000,
      currency: "GBP",
      extended_checkout_offered: false,
      extended_checkout_price_minor: null,
      is_featured: false,
      status: "approved",
      images: imgs(I.c, I.d, I.e),
      cover_photo_url: img(I.c),
    },
    {
      id: "PR022",
      slug: "katampe-hill-residence",
      name: "Katampe Hill Residence",
      branded_name: "Katampe Hill Residence",
      building_name: "Katampe Estate",
      city: "Abuja",
      neighbourhood: "Katampe",
      neighbourhood_slug: slugify("Katampe"),
      building_slug: slugify("Katampe Estate"),
      country: "Nigeria",
      description: "A hillside three-bedroom retreat with a panoramic infinity pool overlooking the Katampe valley. Open-plan living with double-volume ceilings, a wine cellar, and a private study. Gated estate with jogging trails.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Infinity pool", "Wine cellar", "Study", "Terrace", "Parking", "24/7 security", "Generator backup"],
      route_note: "30 min from ABV. On the hill inside Katampe Estate.",
      bedrooms: 3,
      sleeps: 6,
      nightly_rate_minor: 42000,
      deposit_minor: 20000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 16800,
      is_featured: true,
      status: "approved",
      images: imgs(I.f, I.g, I.h),
      cover_photo_url: img(I.f),
    },
    {
      id: "PR023",
      slug: "durumi-garden-apartment",
      name: "Durumi Garden Apartment",
      branded_name: "Durumi Garden Apartment",
      building_name: "Sunflower Estate",
      city: "Abuja",
      neighbourhood: "Durumi",
      neighbourhood_slug: slugify("Durumi"),
      building_slug: slugify("Sunflower Estate"),
      country: "Nigeria",
      description: "A one-bedroom garden apartment in a quiet Durumi estate. Lots of natural light, a galley kitchen finished in sage green tiles, and a patio overlooking manicured lawns. Five minutes from the Durumi market.",
      amenities: ["WiFi", "Air conditioning", "Kitchen", "Garden", "Patio", "Laundry", "Security", "Parking"],
      route_note: "25 min from ABV. Inside Sunflower Estate, Durumi.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 20000,
      deposit_minor: 10000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 8000,
      is_featured: false,
      status: "approved",
      images: imgs(I.i, I.j, I.k),
      cover_photo_url: img(I.i),
    },
    {
      id: "PR024",
      slug: "guzape-contemporary",
      name: "Guzape Contemporary",
      branded_name: "Guzape Contemporary",
      building_name: "Hilltop Mews",
      city: "Abuja",
      neighbourhood: "Guzape",
      neighbourhood_slug: slugify("Guzape"),
      building_slug: slugify("Hilltop Mews"),
      country: "Nigeria",
      description: "A contemporary two-bedroom mews house in up-and-coming Guzape. Polished concrete floors, a chef's kitchen with an island, and a roof terrace with views towards Aso Rock. Popular with diplomats and NGO directors.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Roof terrace", "Smart home", "Workspace", "Parking", "Security"],
      route_note: "25 min from ABV. On the hill in Guzape District.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 35000,
      deposit_minor: 18000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 14000,
      is_featured: false,
      status: "approved",
      images: imgs(I.l, I.m, I.n),
      cover_photo_url: img(I.l),
    },
    {
      id: "PR025",
      slug: "maitama-diplomatic-suite",
      name: "Maitama Diplomatic Suite",
      branded_name: "Maitama Diplomatic Suite",
      building_name: "Diplomatic Drive Estate",
      city: "Abuja",
      neighbourhood: "Maitama",
      neighbourhood_slug: slugify("Maitama"),
      building_slug: slugify("Diplomatic Drive Estate"),
      country: "Nigeria",
      description: "A two-bedroom suite on Maitama's Diplomatic Drive, home to over a dozen embassies. The apartment pairs British colonial plantation shutters with Hausa embroidered textiles. A rooftop infinity pool overlooks the embassy quarter.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Infinity pool", "Rooftop terrace", "Gym", "Parking", "Housekeeping", "24/7 security"],
      route_note: "22 min from ABV. On Diplomatic Drive, Maitama.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 34000,
      deposit_minor: 15000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 13600,
      is_featured: true,
      status: "approved",
      images: imgs(I.o, I.p, I.q),
      cover_photo_url: img(I.o),
    },
    {
      id: "PR026",
      slug: "gra-diplomatic-terrace",
      name: "GRA Diplomatic Terrace",
      branded_name: "GRA Diplomatic Terrace",
      building_name: "Constitutional Avenue Court",
      city: "Abuja",
      neighbourhood: "GRA",
      neighbourhood_slug: slugify("GRA"),
      building_slug: slugify("Constitutional Avenue Court"),
      country: "Nigeria",
      description: "A three-bedroom apartment on Constitutional Avenue in the heart of GRA. Italian marble throughout, a formal dining room that seats ten, and a terrace large enough for entertaining. Walking distance to the State House.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Formal dining", "Terrace", "Pool", "Gym", "Parking", "Butler service", "Generator backup"],
      route_note: "25 min from ABV. On Constitutional Avenue, GRA.",
      bedrooms: 3,
      sleeps: 6,
      nightly_rate_minor: 58000,
      deposit_minor: 25000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 23200,
      is_featured: false,
      status: "approved",
      images: imgs(I.r, I.s, I.t),
      cover_photo_url: img(I.r),
    },
    {
      id: "PR027",
      slug: "central-district-presidential",
      name: "Central District Presidential",
      branded_name: "Central District Presidential",
      building_name: "Shehu Musa Yar'Adua Towers",
      city: "Abuja",
      neighbourhood: "Central District",
      neighbourhood_slug: slugify("Central District"),
      building_slug: slugify("Shehu Musa YarAdua Towers"),
      country: "Nigeria",
      description: "The flagship four-bedroom residence occupying the entire top floor of a Central District landmark. Private elevator access, a panoramic living room, a library, a media room, and a 360-degree terrace with views across the entire capital.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Private elevator", "Library", "Media room", "Panoramic terrace", "Wine cellar", "Pool", "Gym", "Valet parking", "Concierge", "24/7 security"],
      route_note: "18 min from ABV. Shehu Musa Yar'Adua Towers, Central District.",
      bedrooms: 4,
      sleeps: 8,
      nightly_rate_minor: 80000,
      deposit_minor: 35000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 32000,
      is_featured: true,
      status: "approved",
      images: imgs(I.a, I.c, I.e),
      cover_photo_url: img(I.a),
    },
    {
      id: "PR028",
      slug: "asokoro-garden-terrace",
      name: "Asokoro Garden Terrace",
      branded_name: "Asokoro Garden Terrace",
      building_name: "Garden Terraces Estate",
      city: "Abuja",
      neighbourhood: "Asokoro",
      neighbourhood_slug: slugify("Asokoro"),
      building_slug: slugify("Garden Terraces Estate"),
      country: "Nigeria",
      description: "A bright two-bedroom garden terrace in one of Asokoro's most sought-after estates. Open-plan living, a marble kitchen island, and a private garden with a koi pond. Short walk to the Asokoro green market.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Garden", "Koi pond", "Workspace", "Parking", "Security", "Generator backup"],
      route_note: "25 min from ABV. Inside Garden Terraces Estate, Asokoro.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 40000,
      deposit_minor: 20000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 16000,
      is_featured: false,
      status: "approved",
      images: imgs(I.b, I.d, I.f),
      cover_photo_url: img(I.b),
    },
    {
      id: "PR029",
      slug: "wuse-2-city-loft",
      name: "Wuse 2 City Loft",
      branded_name: "Wuse 2 City Loft",
      building_name: "Ibrahim Babangida Boulevard",
      city: "Abuja",
      neighbourhood: "Wuse 2",
      neighbourhood_slug: slugify("Wuse 2"),
      building_slug: slugify("Ibrahim Babangida Boulevard"),
      country: "Nigeria",
      description: "A loft-style two-bedroom on the bustling Ibrahim Babangida Boulevard. Industrial exposed ducts, a concrete feature wall, and a balcony bar perfect for evening sundowners. Steps from the best nightlife in Wuse 2.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Balcony bar", "Smart TV", "Workspace", "Parking", "Security"],
      route_note: "20 min from ABV. On Ibrahim Babangida Boulevard, Wuse 2.",
      bedrooms: 2,
      sleeps: 4,
      nightly_rate_minor: 28000,
      deposit_minor: 15000,
      currency: "GBP",
      extended_checkout_offered: true,
      extended_checkout_price_minor: 11200,
      is_featured: false,
      status: "approved",
      images: imgs(I.g, I.i, I.k),
      cover_photo_url: img(I.g),
    },
    {
      id: "PR030",
      slug: "jabi-lake-penthouse",
      name: "Jabi Lake Penthouse",
      branded_name: "Jabi Lake Penthouse",
      building_name: "Jabi Lake Tower",
      city: "Abuja",
      neighbourhood: "Jabi",
      neighbourhood_slug: slugify("Jabi"),
      building_slug: slugify("Jabi Lake Tower"),
      country: "Nigeria",
      description: "A show-stopping penthouse on the 14th floor of the Jabi Lake Tower. Glass walls on three sides, a private hot tub on the terrace, and a fully automated smart home system. The building has a rooftop helipad.",
      amenities: ["WiFi", "Air conditioning", "Washer", "Full kitchen", "Private hot tub", "Smart home", "Rooftop terrace", "Helipad access", "Pool", "Gym", "Valet parking", "Concierge", "24/7 security"],
      route_note: "20 min from ABV. 14th floor, Jabi Lake Tower.",
      bedrooms: 1,
      sleeps: 2,
      nightly_rate_minor: 22000,
      deposit_minor: 12000,
      currency: "GBP",
      extended_checkout_offered: false,
      extended_checkout_price_minor: null,
      is_featured: false,
      status: "approved",
      images: imgs(I.h, I.j, I.l),
      cover_photo_url: img(I.h),
    },
  ];
}

export function getSeedReservations(): SeedReservation[] {
  return [
    // ── Existing reservations (R001–R005) — unchanged ──
    { id: "R001", property_id: "PR001", check_in: "2026-06-18", check_out: "2026-06-22", status: "confirmed" },
    { id: "R002", property_id: "PR002", check_in: "2026-06-20", check_out: "2026-06-24", status: "confirmed" },
    { id: "R003", property_id: "PR001", check_in: "2026-06-25", check_out: "2026-06-30", status: "confirmed" },
    { id: "R004", property_id: "PR002", check_in: "2026-07-01", check_out: "2026-07-04", status: "confirmed" },
    { id: "R005", property_id: "PR004", check_in: "2026-07-10", check_out: "2026-07-14", status: "confirmed" },

    // ── New reservations (R006–R020) ──
    { id: "R006", property_id: "PR003", check_in: "2026-06-12", check_out: "2026-06-15", status: "completed" },
    { id: "R007", property_id: "PR005", check_in: "2026-06-08", check_out: "2026-06-12", status: "completed" },
    { id: "R008", property_id: "PR006", check_in: "2026-06-05", check_out: "2026-06-09", status: "completed" },
    { id: "R009", property_id: "PR007", check_in: "2026-07-01", check_out: "2026-07-05", status: "confirmed" },
    { id: "R010", property_id: "PR008", check_in: "2026-07-03", check_out: "2026-07-07", status: "confirmed" },
    { id: "R011", property_id: "PR009", check_in: "2026-07-15", check_out: "2026-07-18", status: "confirmed" },
    { id: "R012", property_id: "PR010", check_in: "2026-07-20", check_out: "2026-07-25", status: "confirmed" },
    { id: "R013", property_id: "PR011", check_in: "2026-07-25", check_out: "2026-07-28", status: "confirmed" },
    { id: "R014", property_id: "PR004", check_in: "2026-07-15", check_out: "2026-07-19", status: "cancelled" },
    { id: "R015", property_id: "PR003", check_in: "2026-07-20", check_out: "2026-07-24", status: "cancelled" },
    { id: "R016", property_id: "PR012", check_in: "2026-08-01", check_out: "2026-08-05", status: "confirmed" },
    { id: "R017", property_id: "PR013", check_in: "2026-08-10", check_out: "2026-08-14", status: "confirmed" },
    { id: "R018", property_id: "PR014", check_in: "2026-08-20", check_out: "2026-08-24", status: "confirmed" },
    { id: "R019", property_id: "PR001", check_in: "2026-09-01", check_out: "2026-09-05", status: "confirmed" },
    { id: "R020", property_id: "PR002", check_in: "2026-09-10", check_out: "2026-09-14", status: "confirmed" },
  ];
}

export function getSeedBlocks(): SeedBlock[] {
  return [
    // ── Existing blocks ──
    { property_id: "PR003", starts: "2026-07-01", ends: "2026-07-10", source: "owner" },
    { property_id: "PR006", starts: "2026-08-15", ends: "2026-08-31", source: "owner" },

    // ── New blocks ──
    { property_id: "PR001", starts: "2026-07-05", ends: "2026-07-08", source: "maintenance" },
    { property_id: "PR005", starts: "2026-06-20", ends: "2026-06-25", source: "owner" },
    { property_id: "PR008", starts: "2026-08-20", ends: "2026-08-27", source: "maintenance" },
    { property_id: "PR010", starts: "2026-09-05", ends: "2026-09-10", source: "owner" },
    { property_id: "PR015", starts: "2026-06-15", ends: "2026-06-22", source: "owner" },
  ];
}

export function getSeedOperators(): SeedOperator[] {
  return [
    { id: "OP001", name: "Adaora Mensah", phone: "+2348023012345", city: "Lagos", email: "adaora.m@checkinbliss.com" },
    { id: "OP002", name: "Tunde Ogunlade", phone: "+2348034567890", city: "Lagos", email: "tunde.o@checkinbliss.com" },
    { id: "OP003", name: "Funke Adeyemi", phone: "+2348056789012", city: "Abuja", email: "funke.a@checkinbliss.com" },
    { id: "OP004", name: "Chibueze Nnamdi", phone: "+2348090123456", city: "Abuja", email: "chibueze.n@checkinbliss.com" },
    { id: "OP005", name: "Yetunde Bakare", phone: "+2347012345678", city: "Lagos", email: "yetunde.b@checkinbliss.com" },
    { id: "OP006", name: "Ibrahim Danjuma", phone: "+2348031234567", city: "Abuja", email: "ibrahim.d@checkinbliss.com" },
  ];
}

export function getSeedInspections(): SeedInspection[] {
  return [
    {
      id: "IN001",
      property_id: "PR003",
      property_name: "The Palms Maisonette",
      unit: "Unit 1",
      guest_name: "Amara Obi",
      checkout_date: "2026-06-15",
      checkout_time: "11:00",
      status: "completed",
      confirmed_checkout_time: "11:05",
    },
    {
      id: "IN002",
      property_id: "PR005",
      property_name: "Maitama Garden Studios",
      unit: "Studio B",
      guest_name: "Kola Ogun",
      checkout_date: "2026-06-12",
      checkout_time: "10:00",
      status: "completed",
      confirmed_checkout_time: "10:10",
    },
    {
      id: "IN003",
      property_id: "PR006",
      property_name: "Central Abuja Penthouse",
      unit: "Penthouse",
      guest_name: "Zainab Bello",
      checkout_date: "2026-06-09",
      checkout_time: "12:00",
      status: "completed",
      confirmed_checkout_time: "12:00",
    },
    {
      id: "IN004",
      property_id: "PR001",
      property_name: "Lagoon View Loft",
      unit: "Unit 1",
      guest_name: "Emeka Nwosu",
      checkout_date: "2026-06-30",
      checkout_time: "11:00",
      status: "pending",
      confirmed_checkout_time: null,
    },
    {
      id: "IN005",
      property_id: "PR011",
      property_name: "Banana Island Villa",
      unit: "Main Villa",
      guest_name: "Folake Adeyemi",
      checkout_date: "2026-07-28",
      checkout_time: "10:00",
      status: "pending",
      confirmed_checkout_time: null,
    },
    {
      id: "IN006",
      property_id: "PR022",
      property_name: "Katampe Hill Residence",
      unit: "Hill House",
      guest_name: "Ngozi Okonkwo",
      checkout_date: "2026-08-14",
      checkout_time: "11:00",
      status: "in_progress",
      confirmed_checkout_time: null,
    },
  ];
}

export function getSeedDamageClaims(): SeedDamageClaim[] {
  return [
    {
      id: "DC001",
      reservation_id: "R006",
      property_name: "The Palms Maisonette",
      property_id: "PR003",
      guest_name: "Amara Obi",
      guest_email: "amara.o@email.com",
      booking_ref: "PAY-2026-0612",
      stay_dates: "Jun 12-15",
      description: "Smashed wine glass on marble floor — small chip in the stone. Photos attached of the affected area.",
      estimated_cost_minor: 12000,
      operator_notes: "Confirmed chip in kitchen floor marble. Repair quote obtained from Stone Restoration Services.",
      photo_count: 2,
      admin_decision: "approved",
      adjusted_amount_minor: null,
      dispute_status: "none",
      submitted_at: "2026-06-16T10:30:00Z",
      decided_at: "2026-06-17T14:00:00Z",
      decided_by: "Admin",
      photos: [img(I.m), img(I.n)],
    },
    {
      id: "DC002",
      reservation_id: "R007",
      property_name: "Maitama Garden Studios",
      property_id: "PR005",
      guest_name: "Kola Ogun",
      guest_email: "kola.o@email.com",
      booking_ref: "PAY-2026-0608",
      stay_dates: "Jun 8-12",
      description: "Bathroom cabinet door came off its hinges. Guest reported it on departure. Minor repair needed.",
      estimated_cost_minor: 5000,
      operator_notes: "Hinges were loose. Can be fixed by handyman — no materials cost.",
      photo_count: 1,
      admin_decision: "approved",
      adjusted_amount_minor: null,
      dispute_status: "none",
      submitted_at: "2026-06-13T09:15:00Z",
      decided_at: "2026-06-14T11:00:00Z",
      decided_by: "Admin",
      photos: [img(I.o)],
    },
    {
      id: "DC003",
      reservation_id: "R008",
      property_name: "Central Abuja Penthouse",
      property_id: "PR006",
      guest_name: "Zainab Bello",
      guest_email: "zainab.b@email.com",
      booking_ref: "PAY-2026-0605",
      stay_dates: "Jun 5-9",
      description: "Stain on the living room rug. Attempted cleaning did not fully remove it. Professional deep clean or replacement may be required.",
      estimated_cost_minor: 25000,
      operator_notes: "Red wine stain on wool rug. Professional cleaner quoted 8,000. Full replacement would be 25,000.",
      photo_count: 2,
      admin_decision: "adjusted",
      adjusted_amount_minor: 8000,
      dispute_status: "none",
      submitted_at: "2026-06-10T14:00:00Z",
      decided_at: "2026-06-12T09:30:00Z",
      decided_by: "Admin",
      photos: [img(I.p), img(I.q)],
    },
    {
      id: "DC004",
      reservation_id: "R005",
      property_name: "GRA Executive Suite",
      property_id: "PR004",
      guest_name: "Kola Ogun",
      guest_email: "kola.o@email.com",
      booking_ref: "PAY-2026-0710",
      stay_dates: "Jul 10-14",
      description: "Guest disputes charge for a broken glass table — claims it was already cracked. Investigating with photos from pre-checkout inspection.",
      estimated_cost_minor: 35000,
      operator_notes: "Pre-checkout inspection photos show no crack. Guest is disputing via email.",
      photo_count: 3,
      admin_decision: "pending",
      adjusted_amount_minor: null,
      dispute_status: "open",
      submitted_at: "2026-07-15T08:00:00Z",
      decided_at: null,
      decided_by: null,
      photos: [img(I.r), img(I.s), img(I.t)],
    },
  ];
}
