-- 0018_phase7_schema.sql
-- Phase 7 — real-mode schema drift fixes.
--
-- Three pieces the application code already assumes exist but the schema does
-- not currently provide. Closing the gap so real-mode stops failing with
-- "schema cache" / 404s on operators + assigned_cities, on signup profile
-- upserts writing country_of_residence, and on the booking lookup route
-- reading booking_groups.reference.
--
-- 1. operators table — admin operator create/suspend/lookup + assigned_cities
--    array. Code in actions/operators.ts and app/api/admin/operators/route.ts
--    already speaks this shape; operator_assignments remains the per-city
--    detail (PK on (operator_id, city)).
--
-- 2. profiles.country_of_residence — written by actions/auth.ts on signup
--    and on first-session auto-profile upsert.
--
-- 3. booking_groups.reference — 8-char base32, unique, populated by book_stays()
--    inside the same transaction that creates the reservations. reservations
--    already has its own per-row .reference (same format); the group's
--    reference is shared across all reservations in that checkout so the
--    confirmation page and lookup route can address the whole group.

-- ------------------------------------------------------------------ --
--  1. operators                                                      --
-- ------------------------------------------------------------------ --

create table if not exists operators (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid unique references profiles(id) on delete cascade,
  name text not null,
  email text not null unique,
  assigned_cities text[] not null default '{}',
  city text,
  status text not null default 'onboarding',
  quality_score int not null default 0,
  inspections_done int not null default 0,
  verified_count int not null default 0,
  properties_count int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists operators_profile_id_idx on operators(profile_id);
create index if not exists operators_status_idx on operators(status);

comment on table operators is
  'Per-operator operational record (separate from the auth profile). The assigned_cities
   array here is the dashboard-facing summary; operator_assignments remains the per-city
   source of truth used by RLS (has_city_access).';
comment on column operators.assigned_cities is
  'City list surfaced in admin / dashboard UI; mirrors operator_assignments rows.';

-- ------------------------------------------------------------------ --
--  2. profiles.country_of_residence                                  --
-- ------------------------------------------------------------------ --

alter table profiles
  add column if not exists country_of_residence text;

comment on column profiles.country_of_residence is
  'ISO country the user resides in (free-text — signup form does not validate the
   controlled-vocabulary list; analytics + future localisation use this).';

-- ------------------------------------------------------------------ --
--  3. booking_groups.reference                                       --
-- ------------------------------------------------------------------ --

alter table booking_groups
  add column if not exists reference text;

create unique index if not exists booking_groups_reference_uidx
  on booking_groups(reference)
  where reference is not null;

comment on column booking_groups.reference is
  '8-char base32 group reference, shared across all reservations in a multi-item
   checkout. Generated by book_stays() inside the booking transaction; the same
   value as the first reservation''s reference (single-item checkouts share both).';
